export const QUERY_CUSTOMERS = 'QUERY_CUSTOMERS';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_COSTUMER = 'UPDATE_COSTUMER';
export const START_DELETE_COSTUMER = 'START_DELETE_COSTUMER';
export const DELETE_COSTUMER = 'DELETE_COSTUMER';
export const CANCEL_DELETE_COSTUMER = 'CANCEL_DELETE_COSTUMER';